### PR TITLE
TYPO3 v10 compat 

### PR DESCRIPTION
**Pull request by fjacobi**
Have to quit for today, will take a look at updating the mailings on sunday for usage of FluidEmail

### CODE REVIEW

**Comment by mbrodala** [comment]
Switching to `FluidEmail` should be done with backwards compat, otherwise we loose compat to TYPO3v9 and TYPO3v8.

**Comment by mbrodala** [comment]
Switching to draft mode since it sounds like you will add more changes.

**Comment by fjacobi** [comment]
Due to personal reasons I can't put more time into it, so properly implementing FluidEmail is out.
But I built a quick feature switch for the newer logic and the exception handling.
I'm not 100% sure about the debug message of SentMessage, but the TransportExceptionInterface has no message, so it might be better than nothing?

**Comment by mbrodala** [comment]
All of this and much more was combined in #68 now.

**Pull request closed without merging**
